### ISSUE TITLE
Lzma lib not found on CentOS 6.6

### ISSUE THREAD

**Issue by vishal-biyani** [miguno/wirbelsturm-rpm-storm#2]
While running ` storm-rpm.sh` I get below error on CentOS 6.6. Bootstrap runs fine. 

```
/home/vagrant/.rvm/gems/ruby-2.0.0-p195/gems/ffi-1.9.0/lib/ffi/library.rb:123:in `block in ffi_lib': Could not open library 'lzma.so.5': lzma.so.5: cannot open shared object file: No such file or directory. (LoadError)
Could not open library 'liblzma.so.5': liblzma.so.5: cannot open shared object file: No such file or directory.
Could not open library 'lzma.so': lzma.so: cannot open shared object file: No such file or directory.
Could not open library 'liblzma.so': liblzma.so: cannot open shared object file: No such file or directory.
Could not open library 'lzma': lzma: cannot open shared object file: No such file or directory
	from /home/vagrant/.rvm/gems/ruby-2.0.0-p195/gems/ffi-1.9.0/lib/ffi/library.rb:90:in `map'
	from /home/vagrant/.rvm/gems/ruby-2.0.0-p195/gems/ffi-1.9.0/lib/ffi/library.rb:90:in `ffi_lib'
	from /home/vagrant/.rvm/gems/ruby-2.0.0-p195/gems/ruby-xz-0.2.3/lib/xz/lib_lzma.rb:84:in `<module:LibLZMA>'
	from /home/vagrant/.rvm/gems/ruby-2.0.0-p195/gems/ruby-xz-0.2.3/lib/xz/lib_lzma.rb:31:in `<module:XZ>'
	from /home/vagrant/.rvm/gems/ruby-2.0.0-p195/gems/ruby-xz-0.2.3/lib/xz/lib_lzma.rb:28:in `<top (required)>'
	from /home/vagrant/.rvm/gems/ruby-2.0.0-p195/gems/ruby-xz-0.2.3/lib/xz.rb:450:in `require_relative'
	from /home/vagrant/.rvm/gems/ruby-2.0.0-p195/gems/ruby-xz-0.2.3/lib/xz.rb:450:in `<top (required)>'
	from /home/vagrant/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
	from /home/vagrant/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
	from /home/vagrant/.rvm/gems/ruby-2.0.0-p195/gems/backports-3.3.3/lib/backports/tools.rb:328:in `require_with_backports'
	from /home/vagrant/.rvm/gems/ruby-2.0.0-p195/gems/fpm-1.5.0/lib/fpm/package/freebsd.rb:7:in `<top (required)>'
	from /home/vagrant/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
	from /home/vagrant/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
	from /home/vagrant/.rvm/gems/ruby-2.0.0-p195/gems/backports-3.3.3/lib/backports/tools.rb:328:in `require_with_backports'
	from /home/vagrant/.rvm/gems/ruby-2.0.0-p195/gems/fpm-1.5.0/lib/fpm.rb:19:in `<top (required)>'
	from /home/vagrant/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
	from /home/vagrant/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
	from /home/vagrant/.rvm/gems/ruby-2.0.0-p195/gems/fpm-1.5.0/bin/fpm:5:in `<top (required)>'
	from /home/vagrant/.rvm/gems/ruby-2.0.0-p195/bin/fpm:23:in `load'
	from /home/vagrant/.rvm/gems/ruby-2.0.0-p195/bin/fpm:23:in `<main>'
	from /home/vagrant/.rvm/gems/ruby-2.0.0-p195/bin/ruby_executable_hooks:15:in `eval'
	from /home/vagrant/.rvm/gems/ruby-2.0.0-p195/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by vishal-biyani** [comment]
This is related to bug https://github.com/jordansissel/fpm/issues/1090 and the comment https://github.com/jordansissel/fpm/issues/1090#issuecomment-213595604 resolves it. Specifically I had to get to ruby 1.9.3 and fpm 1.4.0 - the last two commands in comment.
